name: app_cerimoniarios
description: App para gestão de escalas dos cerimoniários
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.3
  firebase_auth_web: ^5.8.13
  cloud_firestore: ^4.15.3
  firebase_messaging: ^14.7.7
  firebase_messaging_web: ^3.5.18
  flutter_local_notifications: ^15.1.1
  http: ^0.13.6
  js: ^0.6.7


  # Calendário
  table_calendar: ^3.1.3

  # Ícones iOS
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
